### ISSUE TITLE
Package version mismatch with laravel

### ISSUE THREAD

**Issue by scs75** [goetas-webservices/xsd2php#1]
I've tried to install xsd2php into a laravel 5.2 framwork. Error message said:
Conclusion: remove symfony/event-dispatcher v3.1.0

I looked into the dependencies, and the wsdl-reader package require symfony/event-dispatcher ^2.2. Laravel already has a symfony/event-dispatcher 3.1.0.
How can I resolve this version issue?

**Comment by goetas** [comment]
hi, i have updated the deps, now should work with `symfony/event-dispatcher:^2.4|symfony/event-dispatcher:^3.0`

Can you retry?

**Comment by scs75** [comment]
Working. Thank you.
