### ISSUE TITLE
OTA XSD definitions URL is not accessible

### ISSUE THREAD

**Issue by bperel** [goetas-webservices/xsd2php#106]
Hello,

I don't know since when but the URL that is referenced in the README (http://opentravel.org/Specifications/OnlineXmlSchema.aspx) points to a HTTP 403 page.

**Comment by martijn80** [comment]
The overview moved I guess, I've found all specs here : 

http://www.opentravelmodel.net/pubs/specifications/PastSpecs.html

Clicking the links got me redirected to the latest spec, but I've found a workaround to view these listed specs via some URL wizardry like this : 

The 2003A XSD are here (the click the link icon)

http://www.opentravelmodel.net/pubs/specifications/OnlinePublicationDetails.html?spec=2003A&specType=OTA_1_0

So change the URL to your needs.
