### ISSUE TITLE
same name in type's name and element's name property

### ISSUE THREAD

**Issue by fikusz01** [goetas-webservices/xsd2php#111]
Given the folloving xsd structure
````
<!-- original naming from xsd -->
<xs:element name="TrainActivity" type="TrainActivityType"></xs:element>
<xs:element name="TrainActivityType">
	<xs:simpleType>
		<xs:restriction base="xs:string">
			<xs:minLength value="4"/>
			<xs:maxLength value="4"/>
		</xs:restriction>
	</xs:simpleType>
</xs:element>			
<xs:complexType name="TrainActivityType">
	<xs:sequence>
		<xs:element ref="TrainActivityType"/>
		<xs:element ref="AssociatedAttachedTrainID" minOccurs="0"/>
		<xs:element ref="AssociatedAttachedOTN" minOccurs="0"/>
	</xs:sequence>
</xs:complexType>
````
the converter generates the following:
- php class: TrainActivity extends TrainActivityType
- php class: TrainActivityType
- jms yaml: TrainActivity (no property)
- jms yaml: TrainActivityType (with 3 properties)

The problem is that neither the parser not the generator deals with TrainActivityType's value, because the yaml of the TrainActivityType complex type overrides the yaml of the element TrainActivityType.

If I rename the name of the TrainActivityType complex type as the following, everting works great:
````
<!-- modified naming from xsd -->
<xs:element name="TrainActivity" type="TrainActivityType2"></xs:element>
<xs:element name="TrainActivityType">
	<xs:simpleType>
		<xs:restriction base="xs:string">
			<xs:minLength value="4"/>
			<xs:maxLength value="4"/>
		</xs:restriction>
	</xs:simpleType>
</xs:element>			
<xs:complexType name="TrainActivityType2">
	<xs:sequence>
		<xs:element ref="TrainActivityType"/>
		<xs:element ref="AssociatedAttachedTrainID" minOccurs="0"/>
		<xs:element ref="AssociatedAttachedOTN" minOccurs="0"/>
	</xs:sequence>
</xs:complexType>
````
This xsd is an international standard and validates well.

**Comment by goetas** [comment]
please use the long naming strategy in your configuration file (see https://github.com/goetas-webservices/xsd2php#naming-strategy)
