### ISSUE TITLE
types used in php classes are different than types used in the yaml configs

### ISSUE THREAD

**Issue by fikusz01** [goetas-webservices/xsd2php#117]
I'm writing a very complex reader/generator. I have an overcomplicated xsd - describing an international standard.
(v2.2.4 - https://railnetat-my.sharepoint.com/:f:/g/personal/taftaptsi_rne_eu/EtPwHWyVjLVHhqjp6h23zysBdgytr3emoONWZ-j_Y1mEWQ?e=lWGqfU)

When I transform the xsd to php (using naming_strategy: long), I see that the php classes look nice, base types such as integer/string/etc in the xsd are integer/string/etc in the class as well. But in the corresponding yaml file, instead of the integer/string/etc, there is a custom model used (only with a "->value()" getter).

This makes writing xml-s very painful. Do you have any advice how can I get yamls typed the same as php classes or vica versa?
Example error I'd like to avoid: `PHP Fatal error:  Call to a member function value() on integer in \vendor\jms\serializer\src\JMS\Serializer\Metadata\PropertyMetadata.php on line 104`

Thanks in advance for any help!

**Comment by goetas** [comment]
can you please provide a reporoducer for this issue?

**Comment by fikusz01** [comment]
I attached a zip with some example code: [xsd-and-yaml-types-are-different.zip](https://github.com/goetas-webservices/xsd2php/files/4836448/xsd-and-yaml-types-are-different.zip)

There is the `CompositIdentifierPlannedTypeType.php` in the `Models` folder. You can see that it's typed with basic types such as `string, int` (and a \DateTime as well, but that one is working well). And there is the `CompositIdentifierPlannedTypeType.yml` yaml in the `JMSMetadata` folder. It uses different types such as `Company, Core, ObjectType, TimetableYear, Variant`. These are only wrappers for a `$__value` data member. If the PHP class would use these in type hints and phpdoc that would be nice, 'cause when you generate an xml, you have to use these wrappers in the setters (JMS insists on calling `->value()` and it fails big time on string and int, and another thing is if you put `null` as `$__value` in the wrapper, then it's serialized with an empty tag, so you have to wrap each line in ˙if`, etc). By the way this should work both in PHP 5.6 and 7.4, so some intermediate solution would be good. I'd like to avoid modifying all the generated codes (~600 class and ~600 yaml).

**Comment by goetas** [comment]
this has been solved probably in https://github.com/goetas-webservices/xsd2php/pull/131. 

if you use the `long_no_conflicts` naming strategy, it should work as expected
