### ISSUE TITLE
Composer requirements version

### ISSUE THREAD

**Issue by mickeymathieson** [goetas-webservices/xsd2php#151]
Is there a chance we could bump up some of the version or expand the scope for some of the dependencies?

```
"php": ">=7.2|^8.0",
"psr/log": "^1.0 | ^2.0 | ^3.0",
```

**Comment by goetas** [comment]
can you create a merge request please?

**Comment by mickeymathieson** [comment]
Sure https://github.com/goetas-webservices/xsd2php/pull/153

**Comment by arthurkirkosa** [comment]
@goetas can this PR be merged?
