### ISSUE TITLE
still uses psr/log:^1.0 - Please add support for psr/log:^3.0 and ^2.0

### ISSUE THREAD

**Issue by op-euga** [goetas-webservices/xsd2php#154]
Cannot update some other packages as your package still just can use psr/log:^1.0
Can you please add support for psr/log:^3.0 or at least ^2.0

**Comment by goetas** [comment]
Can you please create a pull request for it?

**Comment by op-euga** [comment]
I see that the changes are already in the master branch (commit by Mickey commit hash 761f205 - merged by Asmir with commit hash 4d69276) but no version/release was created for that.

**Comment by goetas** [comment]
released
