### ISSUE TITLE
compatible to symfony 7.0

### ISSUE THREAD

**Issue by op-euga** [goetas-webservices/xsd2php#167]
I cannot make update to symfony 7 as of max compatibility to symfony 6 only.
Please make compatible to symfony 7 (composer dependencies)

**Comment by op-euga** [comment]
is there a chance this will be fixed soon?

**Comment by op-euga** [comment]
when will this be available as a release?

**Comment by joni1993** [comment]
If you need it before release you can do this in your composer.json any time:

```
...
"require" : {
...
"goetas-webservices/xsd2php": "dev-master",
...
}
...
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/goetas-webservices/xsd2php.git"
        }
    ]
...

```

**Comment by goetas** [comment]
https://github.com/goetas-webservices/xsd2php/releases/tag/0.4.13

**Comment by op-euga** [comment]
thx for the release
