### ISSUE TITLE
Invalid file names for JMS serializer configuration

### ISSUE THREAD

**Issue by FrankGiesecke** [goetas-webservices/xsd2php#3]
The generated YML-files for the JMS serializer have a invalid format.
The documentation of JMS say, that the file names must have the Formate `Vendor.Package.Foo.(xml|yml)` (see http://jmsyst.com/libs/serializer/master/configuration).

**Comment by goetas** [comment]
This is not fully true, https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/SerializerBuilder.php#L279 allows to have a prefix, so you are not forced to specify always a fully qualified filename

**Comment by FrankGiesecke** [comment]
Oh, thanks for the fast reply.
The code of JMS seems to be better (more understandable) than the documentation.
