### ISSUE TITLE
Support for xs:group

### ISSUE THREAD

**Issue by sgasser** [goetas-webservices/xsd2php#31]
Hi,

xs:group not working with my xsd. Is xs:group (https://www.w3schools.com/xml/el_group.asp) not supported?

Thx

**Comment by goetas** [comment]
it should work... https://github.com/goetas-webservices/xsd-reader/blob/master/src/SchemaReader.php#L176 problems?

**Comment by sgasser** [comment]
I'm using the deprecated package: https://github.com/goetas/xsd2php

Have to upgrade to this...

**Comment by goetas** [comment]
From what I remember, the old package should work too

**Comment by sgasser** [comment]
Thx @goetas for your support.

Here is my xsd including the group "def_generic_response":

[alpinebits.xsd.zip](https://github.com/goetas-webservices/xsd2php/files/941644/alpinebits.xsd.zip)

For example in element OTA_HotelDescriptiveContentNotifRS this group is used but it's missing in the generated files.

**Comment by goetas** [comment]
solved in https://github.com/goetas-webservices/xsd-reader/releases/tag/v0.2.6
