### ISSUE TITLE
Doesn't generate the "@Type"

### ISSUE THREAD

**Issue by eopnetto** [goetas-webservices/xsd2php#35]
Hi, first of all, nice work on this web service!! 
It saved me some hours lol.

So, how to auto generate the "@Type" JMS\Serializer\Annotation??

**Comment by goetas** [comment]
Hi, 
this project does not use JMS Annotation, but generates JMS YAML metadata files. 

Using the parameter `destinations_jms` in the  `config.yml` you can decide in which directory you want to place your metadata files
