### ISSUE TITLE
execute xsd2php on Windows

### ISSUE THREAD

**Issue by MartinNohr** [goetas-webservices/xsd2php#36]
I don't understand how to execute the xsd2php command on Windows.
Any hints?

**Comment by goetas** [comment]
Use virtualbox with a linux inside.. https://www.vagrantup.com/ is a tool to ease the setup of a linux system on windows

**Comment by nerijusza** [comment]
Or use "bat" file(composer automatically generates):
Instead of:
vendor/bin/xsd2php convert config.yml /home/my/ota/OTA_Air*.xsd
use
vendor/bin/xsd2php.bat convert config.yml /home/my/ota/OTA_Air*.xsd

**Comment by goetas** [comment]
thanks @nerijusza
