### ISSUE TITLE
simpleType problem

### ISSUE THREAD

**Issue by mysiar** [goetas-webservices/xsd2php#37]
I try to convert eppcom-1.0.xsd along with other files for epp version 1 protocol but facing odd problem with **simpleType** definitions in eppcom.

```
 [GoetasWebservices\XML\XSDReader\Exception\TypeException]                                                                            
  Can't find type named {urn:ietf:params:xml:ns:eppcom-1.0}#clIDType, at line 222 in epp-1.0.xsd
```

definition in eppcom file exist
```
<simpleType name="clIDType">
    <restriction base="token">
      <minLength value="3"/>
      <maxLength value="16"/>
    </restriction>
  </simpleType>
```

is there any way to map this kind of fields using alias ?

both files app & eppcom attached with extensions added txt

[epp-1.0.xsd.txt](https://github.com/goetas-webservices/xsd2php/files/1204431/epp-1.0.xsd.txt)
[eppcom-1.0.xsd.txt](https://github.com/goetas-webservices/xsd2php/files/1204430/eppcom-1.0.xsd.txt)

**Comment by goetas** [comment]
`<import namespace="urn:ietf:params:xml:ns:eppcom-1.0"/>` in `epp-1.0.xsd` does not specify the path on how to find `eppcom-1.0.xsd`, 

few solutions: 
- edit `epp-1.0.xsd` changing the `import` and adding the location of `eppcom-1.0.xsd`
- if you are generating classes from commandline, try specifying `eppcom-1.0.xsd epp-1.0.xsd` in the path
 if you are generating classes programatically, but using the object instance, make sure to load first  `eppcom-1.0.xsd` and then `epp-1.0.xsd`

**Comment by mysiar** [comment]
thanks for that, just figured it out as well and wanted to publish solution:

missing **schemaLocation="eppcom-1.0.xsd"**
```
<import namespace="urn:ietf:params:xml:ns:eppcom-1.0"
          schemaLocation="eppcom-1.0.xsd"/>
```
