### ISSUE TITLE
IATA NDC schemas 16.2 not working

### ISSUE THREAD

**Issue by nerijusza** [goetas-webservices/xsd2php#38]
This package is really awesome. Tried on some simpler xsd it works perfect. Thank you for your work.

Now trying to use for IATA NDC schemas and it does not work. More about NDC:
http://www.iata.org/whatwedo/airline-distribution/ndc/Pages/default.aspx

Schemas location:
https://github.com/iata-ndc/ndc-xsd-162

Sample xml RQ/RS location:
https://github.com/iata-ndc/ndc-xml-162

Basically you can try deserialize any of sample message and should get error. IATA really big player, and schemas are used by many big systems. So I think is correct.

Can not serialize or deserialize. Fatal error occurs when serializer trying to load generated php class from metadata. I think wrong metadata is generated from xsd.

Added 4 tests. First three tests trying to deserialize sample xml to objects, fourth test trying to serialize created object to xml. Results:

1) Fatal error: Uncaught ReflectionException: Class TestNs\MyApp\SeatAvailabilityRQ\TravelersAType\TravelerAType does not exist in
2) Fatal error: Uncaught ReflectionException: Class TestNs\MyApp\SellerCoreRepType\ContactsAType\ContactAType does not exist in 
3) OK. Trying to deserialize same data as in case "2", but removed xml part which failing.
4) Fatal error: Uncaught ReflectionException: Class TestNs\MyApp\SellerCoreRepType\ContactsAType\ContactAType does not exist in 

Please see attached files.

[files no generated data.zip](https://github.com/goetas-webservices/xsd2php/files/1235989/files.no.generated.data.zip)
[files with generated data.zip](https://github.com/goetas-webservices/xsd2php/files/1235990/files.with.generated.data.zip)

**Comment by goetas** [comment]
can you share the scrip used to generate the classes and metadata?

obviously the `SellerCoreRepType` is missing. now is to figure out why...

**Comment by goetas** [comment]
solved with https://github.com/goetas-webservices/xsd2php/pull/39
