### ISSUE TITLE
xml_list deserialization problems 

### ISSUE THREAD

**Issue by victorgp89** [goetas-webservices/xsd2php#47]
I have this yml file:
![image](https://user-images.githubusercontent.com/9083812/33949500-112b6394-e02a-11e7-95d8-fca6eb1a860f.png)

Execute this: **"scripts": {
    "build": "vendor/bin/xsd2php convert config/test.yml /var/www/igm_client/include/ota/OTA_HotelResRQ.xsd"
  }**

I create the serializer: 
![image](https://user-images.githubusercontent.com/9083812/33949563-3d9ed5dc-e02a-11e7-96ab-33899eb2a8c3.png)

And the metadata is this: 

![image](https://user-images.githubusercontent.com/9083812/33949595-56caa180-e02a-11e7-92c8-7af23ce1fb07.png)

![image](https://user-images.githubusercontent.com/9083812/33949639-775bd2b6-e02a-11e7-8fec-1f6841960d62.png)

When I send this requet:

![image](https://user-images.githubusercontent.com/9083812/33949792-f40e0f54-e02a-11e7-9fa1-f1a680a37a2c.png)

And I have the same issue: 

 PHP Fatal error:  **Uncaught exception 'JMS\\Serializer\\Exception\\RuntimeException' with message 'You must define a type for Igm\\Synergy\\Models\\OTA1\\HotelResRequestType::$echoToken.' in** /var/www/igm_client/vendor/jms/serializer/src/JMS/Serializer/XmlDeserializationVisitor.php:238\nStack trace:\n#0 /var/www/igm_client/vendor/jms/serializer/src/JMS/Serializer/GraphNavigator.php(267): JMS\\Serializer\\XmlDeserializationVisitor->visitProperty(Object(JMS\\Serializer\\Metadata\\PropertyMetadata), Object(SimpleXMLElement), Object(JMS\\Serializer\\DeserializationContext))\n#1 /var/www/igm_client/vendor/jms/serializer/src/JMS/Serializer/Serializer.php(193): JMS\\Serializer\\GraphNavigator->accept(Object(SimpleXMLElement), Array, Object(JMS\\Serializer\\DeserializationContext))\n#2 /var/www/igm_client/vendor/jms/serializer/src/JMS/Serializer/Serializer.php(128): JMS\\Serializer\\Serializer->visit(Object(JMS\\Serializer\\XmlDeserializationVisitor), Object(JMS\\Serializer\\DeserializationContext), Object(SimpleXMLElement), 'xml', Array)\n#3 [internal function]: J in /var/www/igm_client/vendor/jms/serializer/src/JMS/Serializer/XmlDeserializationVisitor.php on line 238

But the metadata and class seems it's ok: 

![image](https://user-images.githubusercontent.com/9083812/33949715-ba3a47ac-e02a-11e7-813f-d0b953573e39.png)

What problem I have?

**Thanks Asmir.**

**Comment by goetas** [comment]
make sure metadata paths/namespaces are properly configured.

**Comment by victorgp89** [comment]
![image](https://user-images.githubusercontent.com/9083812/33950053-a24431e8-e02b-11e7-8ff8-2a6abb557de8.png)

![image](https://user-images.githubusercontent.com/9083812/33950075-b3b2e352-e02b-11e7-94d3-245079147486.png)


![image](https://user-images.githubusercontent.com/9083812/33950121-d2b6e9d8-e02b-11e7-94b9-0cb426fad96b.png)

It seems is all okey not?

**Comment by goetas** [comment]
on `addMetadataDir` is missing the second parameter, the namespace

**Comment by victorgp89** [comment]
I tried I have tried it before: 

But when I did it I returned empty values.

**Igm\Synergy\Models\OTA1\OTAHotelResRQ Object
(
    [echoToken:Igm\Synergy\Models\OTA1\HotelResRequestType:private] => 
    [timeStamp:Igm\Synergy\Models\OTA1\HotelResRequestType:private] => 
    [target:Igm\Synergy\Models\OTA1\HotelResRequestType:private] => 
    [version:Igm\Synergy\Models\OTA1\HotelResRequestType:private] => 
    [transactionIdentifier:Igm\Synergy\Models\OTA1\HotelResRequestType:private] => 
    [sequenceNmbr:Igm\Synergy\Models\OTA1\HotelResRequestType:private] => 
    [transactionStatusCode:Igm\Synergy\Models\OTA1\HotelResRequestType:private] => 
    [primaryLangID:Igm\Synergy\Models\OTA1\HotelResRequestType:private] => 
    [altLangID:Igm\Synergy\Models\OTA1\HotelResRequestType:private] => 
    [retransmissionIndicator:Igm\Synergy\Models\OTA1\HotelResRequestType:private] => 
    [resStatus:Igm\Synergy\Models\OTA1\HotelResRequestType:private] => 
    [holdDuration:Igm\Synergy\Models\OTA1\HotelResRequestType:private] => 
    [pOS:Igm\Synergy\Models\OTA1\HotelResRequestType:private] => Array
        (
        )

    [uniqueID:Igm\Synergy\Models\OTA1\HotelResRequestType:private] => Array
        (
        )

    [hotelReservations:Igm\Synergy\Models\OTA1\HotelResRequestType:private] => 
)**

**Comment by victorgp89** [comment]
The problem is when you add the soap header to the xml.
Is there any solution?
