### ISSUE TITLE
ContainerBuilder not found

### ISSUE THREAD

**Issue by treehousetim** [goetas-webservices/xsd2php#56]
Fatal error: Uncaught Error: Class 'Symfony\Component\DependencyInjection\ContainerBuilder' not found 

$container = new \Symfony\Component\DependencyInjection\ContainerBuilder();

**Comment by treehousetim** [comment]
manually adding these lines to my composer.json require block removed this error.

"symfony/console": "^2.7|^3.0",
		"symfony/dependency-injection": "^2.2|^3.0",
		"symfony/config": "^2.2|^3.0",
		"symfony/yaml": "^2.1|^3.0",

**Comment by goetas** [comment]
can you share your composer json?

**Comment by treehousetim** [comment]
{
	"require": {
		"goetas-webservices/xsd2php-runtime":"~0.2",
		"goetas-webservices/xsd2php":"^0.3"
	  }
}

**Comment by goetas** [comment]
as you can see on https://github.com/goetas-webservices/xsd2php/blob/d7e40e370cd930916fd58e798a55265ac132444c/composer.json#L21
the dependencies are there... so please check your composer installation

**Comment by goetas** [comment]
`goetas-webservices/xsd2php` is recommended  as "dev" dependency.

**Comment by treehousetim** [comment]
I used the composer details from the readme:

> There is one recommended way to install xsd2php via Composer:
> 
> adding the dependency to your composer.json file:
>   "require": {
>       ..
>       "goetas-webservices/xsd2php-runtime":"^0.2.2",
>       ..
>   },
>   "require-dev": {
>       ..
>       "goetas-webservices/xsd2php":"^0.3",
>       ..
>   },
> 

But when that didn't work, I put them both into the require block.

**Comment by goetas** [comment]
closing the issue (IMO is just a some typo somewhere or similar...), we can continue the "debugging" on the closed issue if you have more details to add

**Comment by treehousetim** [comment]
that composer.json file you referenced is where I found the lines to add to my file.  But still, I'm confused as to why they aren't part of the recommended composer.json on the readme.

**Comment by goetas** [comment]
> But still, I'm confused as to why they aren't part of the recommended composer.json on the readme.

they are automatically installed by composer 

The deps specified on the readme are enough

**Comment by goetas** [comment]
(sorry for the stupid question) Did you  run "composer update" after editing the composer.json file?

**Comment by treehousetim** [comment]
sorry for the opening a stupid issue. :/

I just went slowly through the steps of creating a blank project folder with a composer.json file in it and everything worked just fine.  I'm not sure where my brain turned off earlier today.

Thanks for your time, and apologies for wasting it.
