### ISSUE TITLE
composer issues

### ISSUE THREAD

**Issue by steve-rhodes** [goetas-webservices/xsd2php#66]
I've updated this package and can see:
`goetas-webservices/xsd2php            v0.3.2 `
when running `composer show`.

Yet, when I look at the composer.json for this package in the vendor folder I can't see the commits for 0.3.2.

Here's part of my composer.json for the 0.3.2 package:

```
    "doctrine/inflector": "^1.0",
    "zendframework/zend-code": "~2.3",

    "psr/log": "^1.0"
  },
  "require-dev": {
    "phpunit/phpunit": "^4.8|^5.0",
    "jms/serializer": "^1.3",
    "goetas-webservices/xsd2php-runtime": "^0.2.7"
  },
```
according to github for this package it should be:

```
     "doctrine/inflector": "^1.0",
    "zendframework/zend-code": "^3.0.3",

    "psr/log": "^1.0"
  },
  "require-dev": {
    "phpunit/phpunit": "^4.8|^5.0",
    "jms/serializer": "^1.9",
    "goetas-webservices/xsd2php-runtime": "^0.2.7",
    "ext-xmldiff": "*"
  },
```

What am I doing wrong?

I already removed the vendor folder, cleared the cache and reinstalled everything to no avail.

Thanks!

**Comment by cebe** [comment]
here is composer.json of the 0.3.2 tag, it matches exactly what you see:

https://github.com/goetas-webservices/xsd2php/blob/v0.3.2/composer.json#L27-L36
https://github.com/goetas-webservices/xsd2php/blob/889c7d174c712e52f74537172a2bc3248d2e3233/composer.json#L27-L36

if you want to see the same content as github shows on the main page, you need to install latest version or `dev-master`.

**Comment by goetas** [comment]
I consider this as answered, thanks @cebe
