### ISSUE TITLE
Property name in generated class differs from xsd:element name

### ISSUE THREAD

**Issue by david-mock** [goetas-webservices/xsd2php#68]
Hey,

we're using the xsd2php converter to use the generated classes for our SoapClient.
But as it stands, all get* Methods on the objects (which are of the correct type) return `null`.

Upon closer inspections the returned objects have their private property set to `null` but have an appended public property of the correct type. I think this behaviour comes down to a mismatch in the name of the property and the name attribute of the `xsd:element`.

You can see for yourself if you convert the WS-Trust xsd
```
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns="http://www.w3.org/2001/XMLSchema"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            version="1.0">
    <xsd:import namespace="http://schemas.xmlsoap.org/ws/2005/02/trust"
                schemaLocation="http://schemas.xmlsoap.org/ws/2005/02/trust/WS-Trust.xsd"/>
</xsd:schema>
```

In the LifetimeType class the private properties are named `$created` and `$expires` but the name attribute of the corresponding `xsd:element` is "Expires" respectively "Created".
I believe this name mismatch originates from the `\Doctrine\Common\Inflector\Inflector::camelize` function which gets called in `\GoetasWebservices\Xsd\XsdToPhp\Naming\ShortNamingStrategy::getPropertyName.` 

Would it be possible to use the same name in the generated classes so the SoapClient is able to properly match the properties?

**Comment by goetas** [comment]
Are you using https://github.com/goetas-webservices/soap-client or the PHP SoapClient?

If you are using https://github.com/goetas-webservices/soap-client , things should be already automatically handled.

If you are using PHP SoapClient, you can generate the classes using a custom naming strategy and to what you prefer (see https://github.com/goetas-webservices/xsd2php/tree/4ae6efb7eed0df3133f9d2308ba8e8080ebdbaac/src/Naming), but be aware of  issues related to PHP SoapClient and class mapping. (this library was not designed for that use-case even if i know some successful stories)

**Comment by david-mock** [comment]
I'll have a look; thank you for the quick answer!
