### ISSUE TITLE
Deserialize returns empty objects

### ISSUE THREAD

**Issue by Maxwellspb** [goetas-webservices/xsd2php#69]
Hello. Big thanx for your work. This lib helped me to save time on genereating tons of xsd based classes, but I've stuck on deserializing - func returns empty objects (objects with null properties).
Can you help with it?

And another question. Is the deserialize procedure smart enough to return all objects given in XML document from the root to the deepest nested or return specific object from (for example) SOAP envelope wich contains many different objects?

Thank you!

**Comment by goetas** [comment]
Most likely the path for the Metadata files is wrong. Check for typos
This is the most common mistake.

**Comment by Maxwellspb** [comment]
Well, suppose it's not a reason, because metadata paths are copypasted from namespaces. Also script dies on undefined types when metadata is provided incorrectly. I've spent some nervouse hours on that too..
Could this happen because of complex data in XML source? It uses a lot of nested objects in different namespaces and namespace aliaes such as '<'app:SoftVersion'>'.

**Comment by goetas** [comment]
> Could this happen because of complex data in XML source? It uses a lot of nested objects in different namespaces and namespace aliaes such as '<'app:SoftVersion'>'.

I doubt it could be the reason. 

Can you share the code (or part of it) that you use to run the conversion?

**Comment by Maxwellspb** [comment]
Hi again. After some hours of testing I've finally understood my problem.

JMS deserialize func needs specifed object to be a root of XML document. I.e. I can't create product class if its nested inside any parent (and further inside). That makes sense, of course, because there can be multiple products in parent element.
So I think this issue is resolved.

But now I'm facing another problem. I have some xsd files with type **xs:any**.
I've seen similiar case in documentation but after several attempts I still can't make my handler to be invoked.

This is my code:

Handler-class:

```php
namespace components;


use JMS\Serializer\Handler\SubscribingHandlerInterface;
use JMS\Serializer\XmlDeserializationVisitor;
use JMS\Serializer\GraphNavigator;

class AnyHandler implements SubscribingHandlerInterface
{
    public static function getSubscribingMethods()
    {
        return[
            [
                'direction' => GraphNavigator::DIRECTION_DESERIALIZATION,
                'format' => 'xml',
                'type' => 'components\AnyHandler',
                'method' => 'deserializeAny'
            ]
        ];
    }

    public function deserializeAny(XmlDeserializationVisitor $visitor, $data, array $type)
    {
        var_dump($data);
    }
}`
```
This is config.yml

```yml
aliases:
    'http://www.w3.org/2001/XMLSchema':
      any: 'components\AnyHandler'`

```
This is part of index.php
```php
$serializerBuilder->configureHandlers(function (HandlerRegistryInterface $handler) use ($serializerBuilder) {
    $handler->registerSubscribingHandler(new BaseTypesHandler()); // XMLSchema List handling
    $handler->registerSubscribingHandler(new XmlSchemaDateHandler()); // XMLSchema date handling
    $handler->registerSubscribingHandler(new AnyHandler());
});

$serializer = $serializerBuilder->build();


$xml = simplexml_load_file(__DIR__.'/xml/data.XML');


$app = $serializer->deserialize($xml->asXML(), 'customs\Information\ExchangeDocuments\ED_Container\EDContainer', 'xml');`
```
This is a part of xsd:
```xml
<xs:complexType name="DocBodyType">
		<xs:annotation>
			<xs:documentation>Description</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:any processContents="skip">
				<xs:annotation>
					<xs:documentation>Description</xs:documentation>
				</xs:annotation>
			</xs:any>
		</xs:sequence>
	</xs:complexType>
```

I expect $data to be dumped, but nothing happens.

**Comment by goetas** [comment]
Attention that as per documentation (https://github.com/goetas-webservices/xsd2php#dealing-with-xsdanytype-or-xsdanysimpletype) the "any" type is `anyType`, not `any` as you have specified

**Comment by Maxwellspb** [comment]
> Attention that as per documentation (https://github.com/goetas-webservices/xsd2php#dealing-with-xsdanytype-or-xsdanysimpletype) the "any" type is `anyType`, not `any` as you have specified

Is there any working examples of anyType handling?
I do exactly as it said in documentation and test examples, but still have no result.

Let me describe my task.
I'm trying to parse saved backup file of SOAP Envelope with data. I downloaded it's schema to xsd path and made corvertion. As the result I got several classes representing Envelope structure.
But some of them, precisely Header and Body, are just objects with **no** props or methods.
So, when I do deserialization of SOAP message I get Envelope instance with empty Header and Body. The rest content is lost.
In my anyType handler I've placed simple var_dump but it never fires.

Can you help me, where I do wrong?

**Comment by goetas** [comment]
You can have a look to https://github.com/goetas-webservices/soap-client that is doing more or less the same thing (as it is a fully php soap client based on this library).

**Comment by Maxwellspb** [comment]
Unfortunately, I don't have access to WDSL schema. I only have bunch of backup files stored on remote ftp server. I realize this is not the way things should be done. Nevertheless, the libraby works well with defined types, so I may might write some code to grab them from Envelope myself.
Thank you.

**Comment by goetas** [comment]
Cant you get just the RAW XML contained in the env:Body and deserialize that?

**Comment by Maxwellspb** [comment]
Yes, I might do that, but the problem is not only with Envelope, but with all classes with anyType xsd.
Im trying to find out why I can't correctly handle them.
