### ISSUE TITLE
dhl germany xsd serializing incorrect

### ISSUE THREAD

**Issue by Galyam** [goetas-webservices/xsd2php#73]
not quite correct xml is formed

more info at readme:
https://github.com/Galyam/dhl

**Comment by goetas** [comment]
Do you mind adding a bit of formatting to your ticket to make it more understandable?

**Comment by Galyam** [comment]
i tried to add files
but github doesn't support xsd, xml files

**Comment by goetas** [comment]
see https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by Galyam** [comment]
issue updated

**Comment by goetas** [comment]
Are you sure that the XSD is correct? Does the XML passes the validation?

**Comment by Galyam** [comment]
i think xsd is correct
https://github.com/Galyam/dhl/blob/master/services/dhlgermany/external_v2_12.xsd

Xml doesnt pass validation
Invalid content was detected in "Order"
![invalid](https://user-images.githubusercontent.com/1297272/48249243-6f6d3000-e40b-11e8-9535-c2176498f97d.png)

**Comment by goetas** [comment]
interesting... looks that `Order` is in the wrong namespace

**Comment by Galyam** [comment]
to fix it i have to write
`$newXml = str_replace('<Order>', '<ns-42c62173:Order xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">', $newXml);`

**Comment by Galyam** [comment]
Try to deserialize xml into objects, but MessageContentType->stock is null
https://github.com/Galyam/dhl/blob/master/DESERIALIZER.md
