### ISSUE TITLE
Uncaught TypeError: by deserialize

### ISSUE THREAD

**Issue by media-store-net** [goetas-webservices/xsd2php#76]
Hi, at first thanks for great tool.
I get a error by deserialize a XML to PHP Object.

> Uncaught TypeError: Return value of Doctrine\Common\Annotations\AnnotationRegistry::registerFile() must be an instance of Doctrine\Common\Annotations\void, none returned

this error comes only with this line 

`$serializer` = `$serializerBuilder->build();`

what i do wrong?

BuildProcess of PhpClasses and MetaData was succefull...

when you need more Info, let me know.

**Comment by goetas** [comment]
are you using php 7.1?

**Comment by media-store-net** [comment]
php 7.0
which version is required?

**Comment by goetas** [comment]
hmm, something is wrong.. the error you are getting is when you use `void` as return type on php <7.1
But this library should not use `void` as return type...  can you check if some of your php files use `void` as return type?

**Comment by media-store-net** [comment]
This is a Wordpress Plugin that use this MVC Repository as Skelleton https://github.com/amostajo/wordpress-plugin, 
it is possible that one of this files use void as return type.

PS: with PHP 7.2 that works fine, but i get now a other Error, when i try to var_dump a object
`var_dump(new XmlToObject($xml->asXML(), 'sre_oi\controllers\soap\Openimmo'));`

>  Fatal error: Uncaught JMS\Serializer\Exception\RuntimeException: You must define a type for sre_oi\controllers\soap\Openimmo::$uebertragung. in /homepages/3/d164273886/htdocs/devlopment/wp-content/plugins/strobel-real-estate-oi/vendor/jms/serializer/src/JMS/Serializer/XmlDeserializationVisitor.php:251

Here is the metadata that created

> sre_oi\controllers\soap\Openimmo:
    xml_root_name: openimmo
    properties:
        uebertragung:
            expose: true
            access_type: public_method
            serialized_name: uebertragung
            accessor:
                getter: getUebertragung
                setter: setUebertragung
            type: sre_oi\controllers\soap\Uebertragung
        anbieter:
            expose: true
            access_type: public_method
            serialized_name: anbieter
            accessor:
                getter: getAnbieter
                setter: setAnbieter
            xml_list:
                inline: true
                entry_name: anbieter
            type: array<sre_oi\controllers\soap\Anbieter>
        userDefinedSimplefield:
            expose: true
            access_type: public_method
            serialized_name: user_defined_simplefield
            accessor:
                getter: getUserDefinedSimplefield
                setter: setUserDefinedSimplefield
            xml_list:
                inline: true
                entry_name: user_defined_simplefield
            type: array<sre_oi\controllers\soap\UserDefinedSimplefield>
        userDefinedAnyfield:
            expose: true
            access_type: public_method
            serialized_name: user_defined_anyfield
            accessor:
                getter: getUserDefinedAnyfield
                setter: setUserDefinedAnyfield
            xml_list:
                inline: true
                entry_name: user_defined_anyfield
            type: array<sre_oi\controllers\soap\UserDefinedAnyfield>

**is this a part for a other issue ?**

**Comment by goetas** [comment]
The second issue is most likley because the paths were you are storing metadata files are not correct

**Comment by media-store-net** [comment]
OK. The Path of metadata should be the same of the PHP classes?
