### ISSUE TITLE
Conversor

### ISSUE THREAD

**Issue by victorgp89** [goetas-webservices/xsd2php#80]
Hi,

Is it possible with the serializer library, to convert an xml to another xml that best suits what I need?

For example: 

<?xml version="1.0"?>
<b:book xmlns:b="http://example.org">
      <b:title>Cryptonomicon</b:title>
      <b:author>Neil Stephenson</b:author>
</b:book>

To: 

<?xml version="1.0"?>
<b:book title="Cryptomonocon" author="Neil Stephenson">
</b:book>

I simply need a converter that can receive an xml and convert it to another xml that suits my api and be able to work with it more easily.

Then converter to php classes as are habitual.

Thanks for advance,
Victor

**Comment by goetas** [comment]
What you are looking for is https://en.wikipedia.org/wiki/XSLT
