### ISSUE TITLE
Class ... does not exist in ...MetadataFactory.php

### ISSUE THREAD

**Issue by ander-chan** [goetas-webservices/xsd2php#81]
Hi, I'm deserialize the implementation for UBL in my country, It's so wonderful tool generating code (Thanks!!) but my code not find the metadata classes. What i'm wrong !?

```yml
## YAML Template.
xsd2php:
  namespaces:
    'http://www.dian.gov.co/contratos/facturaelectronica/v1': DIAN\UBL
    'http://www.dian.gov.co/contratos/facturaelectronica/v1/Structures': DIAN\UBL\Structures
    'urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2': DIAN\UBL\IANAMIMEMediaType
  ....
  destinations_php: 
    DIAN\UBL: src/DIAN/UBL
    DIAN\UBL\Structures': src/DIAN/UBL/Structures
    DIAN\UBL\CommonExtensionComponents': src/DIAN/UBL/CommonExtensionComponents
    ....
  destinations_jms:
    DIAN\UBL: metadata_/DIAN/UBL
    DIAN\UBL\Structures': metadata_/DIAN/UBL/Structures
    DIAN\UBL\CommonExtensionComponents: metadata_/DIAN/UBL/CommonExtensionComponents
    ....

```
Metadta files:
```.
.
+-- metadata_
|   +-- DIAN
|   |   +-- UBL
|   |   |   +-- Invoice.yml
```
Code:
```php
...
$serializerBuilder->addMetadataDir(__DIR__.'/metadata_/DIAN/UBL','DIAN\\UBL\\');
$xml=file_get_contents("./eg/especific/invoice__paymentTerms__invoicePeriod_pagoA90dias_1dXf-s.xml");
$object = $serializer->deserialize($xml, "Invoice", 'xml');
...
```
[dianubl2.tar.gz](https://github.com/goetas-webservices/xsd2php/files/2774266/dianubl2.tar.gz)

Fatal error:  Uncaught ReflectionException: Class Invoice does not exist in /.../src/MetadataFactory.php:170
Stack trace:
#0 /.../src/MetadataFactory.php(170): ReflectionClass->__construct('Invoice')
```
$php -v
PHP 7.2.14-1+ubuntu16.04.1+deb.sury.org+1...
```

**Comment by goetas** [comment]
I guess, `Invoice` should have the full class name including namespace

**Comment by medicamecanica** [comment]
I was check it, sorry, the the metadatafactory is empty, I debug the **FileLocator** from this post https://github.com/schmittjoh/JMSSerializerBundle/issues/650#issuecomment-381874904 
The **findFileForClass** and  **findAllClasses** has never has been excuted.

**Comment by goetas** [comment]
what about `Invoice` ? which FQCN has?

**Comment by ander-chan** [comment]
I was check it `DIAN/UBL/Invoice`, sorry, the the metadatafactory is empty, I debug the FileLocator from this post schmittjoh/JMSSerializerBundle#650 (comment)
The findFileForClass and findAllClasses has never has been excuted.

**Comment by goetas** [comment]
your php code should be ù
```php
$object = $serializer->deserialize($xml, 'DIAN\UBL\Invoice', 'xml');
```

**Comment by ander-chan** [comment]
yeah!  `$object = $serializer->deserialize($xml, "DIAN\UBL\Invoice", 'xml');`
