### ISSUE TITLE
Work with namespace="##any"

### ISSUE THREAD

**Issue by benito103e** [goetas-webservices/xsd2php#93]
Hi,
I try to generate PHP classes from complexes XSD.
But I don't know how to deal with `namespace="##any"`

Example : ExtensionType in :  
http://www.gdsregistry.org/3.1/schemas/gs1/shared/SharedCommon.xsd

The xsd-reader returns an empty class ComplexType : 
```
ComplexType {#1450 
  #name: "ExtensionType"
  #abstract: false
  #restriction: null
  #extension: null
  #schema: Schema {#1315 }
  #doc: ""
  #attributes: []
  #elements: []
}
```

For informations : the "extension" element can contains further modules like :
- delivery_purchasing_information:deliveryPurchasingInformationModule
- farming_and_processing_information:farmingAndProcessingInformationModule
- ...

These modules have been parsed well.

Thanks

**Comment by goetas** [comment]
Hi. 
Handling `any` in XSD and then porting it to PHP is not generally easy.
I think that the feature you want/need is not yet fully supported.

**Comment by benito103e** [comment]
I understand, the inheritance system in these XSDs is quite complex. 
Thank you anyway.

**Comment by goetas** [comment]
Considering this as answered. If you need to deal with `any`, consider also this https://github.com/goetas-webservices/xsd2php#dealing-with-xsdanytype-or-xsdanysimpletype per to the documentation
