### ISSUE TITLE
Can we remove "symfony/yaml" package from "require"?

### ISSUE THREAD

**Issue by liuxinxil** [goetas-webservices/xsd2php#95]
Can you please remove "symfony/yaml" package from "require"? The reasons are: 
1. Source code of this project doesn't directly depend on "symfony/yaml" package; 
2. Though this project depends on symfony/yaml indirectly through "jms/serializer" which requires "symfony/yaml" in require-dev. Why do you require "symfony/yaml" in xsd2php-runtime?
Thanks!

**Comment by goetas** [comment]
The main reason is that jms serializer requires yaml as optional dependency, while for  xsd2php-runtime is "mandatory" at runtime since the metadata are in YAML format.

Which problems is causing this to you?

**Comment by goetas** [comment]
YAML could be considered "optional" only if you pre-generate all the caches in a "deploy" stage where you still have the dev dependencies... (did not see yet this feature in php frameworks)

**Comment by liuxinxil** [comment]
Dear Asmir,Thank you very much for your super fast response! I really appreciate it!
I'm new to xsd2php project, though I generated the yaml metadata successully, I forgot I need yaml feature when I serialize php to xml. 

Our production ops team don't want to add dependency to symfony/yaml package. So they want me to check whether it's possible to remove it from our production dependency list. I will give them a solid NO then. :)
Thanks and have a great week!
Xin Liu

    On Wednesday, August 7, 2019, 12:48:52 AM CDT, Asmir Mustafic <notifications@github.com> wrote:  
 
 
The main reason is that jms serializer requires yaml as optional dependency, while for xsd2php is "mandatory" at runtime since the metadata are in YAML format.

Which problems is causing this to you?

**Comment by goetas** [comment]
Good. I think that this is solved then

**Comment by liuxinxil** [comment]
Dear Asmir,> xsd2php is "mandatory" at runtime since the metadata are in YAML format.

You mean it's mandatory for xsd2php-runtime package since we need use it to serialize PHP instances to XML string, right? 
Thanks!
Xin Liu
    On Wednesday, August 7, 2019, 12:48:52 AM CDT, Asmir Mustafic <notifications@github.com> wrote:  
 
 
The main reason is that jms serializer requires yaml as optional dependency, while for xsd2php is "mandatory" at runtime since the metadata are in YAML format.

Which problems is causing this to you?

**Comment by goetas** [comment]
Yes, was talking about xsd2php-runtime, my mistake
