### ISSUE TITLE
complex Types with mixed equal true does not pull in text in to the generated php model

### ISSUE THREAD

**Issue by s001dxp** [goetas-webservices/xsd2php#99]
The models that are created does not have a class variable  that contains text nodes when it translates a complexType where mixed is true.
 
Part of my XML looks like this:

```
<et>
   noun derivative of earlier {it}synanthrope{/it}, adjective, “(of plants) adapted to places lived in or frequented by humans,” borrowed from French
   <et_snote>
      <is_required>OK</is_required>
      <t>Term introduced by the German botanist Theodor von Heldreich (1822-1902) in “L’Attique au point de vue des caractères de sa végétation,” {it}Congrès internationale de botanique et d’horticulture, tenu à Paris du 16 au 24 août 1878{/it} (No. 18 of {it}Comptes rendus sténographiques publiés sous les auspices du Comité Central des Congrès et Conférences{/it}), Paris, 1880, p. 116.</t>
   </et_snote>
</et>
```

The php model that are produced will contain the text and fields from the "et_note" tag, but will not bring over the text that is directly inside the "et" tag. (i.e. "noun derivative of earlier...")

The xsd portion that covered this is below:
```
  <xs:complexType name="etType" mixed="true">
    <xs:sequence>
      <xs:element type="et_snoteType" name="et_snote" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
```

How do i get the tool to include this in the models? Or is this a bug?

**Comment by goetas** [comment]
This is something (mixed type definitions) that is not really supported. (it is also not supported by the underlying jms/serializer library) Do not have also an idea on how to do so...

Proposals/contributions are welcome

**Comment by s001dxp** [comment]
@goetas, Thanks for your quick and concise response.
